version: '2'
services:
  web:
   image: wordpress
   links:
   - mysql
   environment:
   - WORDPRESS_DB_PASSWORD=Pa$$w0rd
   ports:
   - "8080:80"
  mysql:
   image: mysql:5.7
   environment:
   - MYSQL_ROOT_PASSWORD=Pa$$w0rd
   - MYSQL_DATABASE=wordpress
